# Generated by Django 4.1.13 on 2024-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('land_area', models.CharField(max_length=100)),
                ('floor_area', models.CharField(max_length=100)),
                ('bedrooms', models.CharField(max_length=100)),
                ('bathrooms', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'combined_tb',
            },
        ),
    ]
